package com.example.model.enums;

public enum ThemeSub {
    RENT, CONSTRUCTION_WORK, COSTS, PROPERTY_TAXES, WATER, GASS, ELECTRICITY, LOAN, FIRE_WOOD, INSURANCE, BOILER, CHIMNEY_SWEEPING, HOME_APPLIANCE, FURNITURE, PATRICK, MURIEL
}
