package com.example.model.enums;

public enum ThemeSub {
    CHOOSE, RENT, CONSTRUCTION_WORK, COSTS, PROPERTY_TAXE, HOUSING_TAXE, WATER, GASS, ELECTRICITY, LOAN, FIRE_WOOD, INSURANCE, BOILER, CHIMNEY_SWEEPING, HOME_APPLIANCE, FURNITURE, PATRICK, MURIEL
}
