package com.example.model.enums;

public enum ThemeGeneral {
    CALUIRE_ET_CUIRE, MEYZIEU, MONTPLAT, HEALTH, FOOD, LEISURE, TRAVEL, TCL, CLOTHING, STATIONARY, OTHER, INCOME_TAXE, PRESENT, COMPUTER, MURIEL, PATRICK
}
